<h2><?php echo $this->__('Quick Order'); ?></h2>

<?php echo $this->__('Search by name or sku: '); ?>
<input id="quickorder_search"  type="text" name="q">

<form id="edge_quickorder" name="edge_quickorder" method='post' action="<?php echo $this->getUrl('edgequickorder/index/addToCart')?>" >
    <div id="itemInput"></div>

    <div id="search_autocomplete_quickorder" class="quickorder-search-autocomplete"></div>
    <script type="text/javascript">
    //<![CDATA[
        var searchFormQuickOrder = new Varien.searchFormQuickOrder('edge_quickorder', 'quickorder_search', '<?php echo $this->__('Search...') ?>');
        searchFormQuickOrder.initAutocomplete('<?php echo $this->getUrl('edgequickorder/index/suggest')?>', 'search_autocomplete_quickorder');
    //]]>
    </script>

    <input type='submit' name='Submit' value='Add all to cart' />

</form>

